require('packer_init')
require('core.options')
require('core.command')
require('core.keymaps')
require('core.autocommands')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.lsp')
require('plugins.nvim-cmp')
require('plugins.nvim-treesitter')
require('plugins.null-ls')
require('plugins.nvim-colorizer')
require('plugins.comment')
require('plugins.dashboard')
vim.cmd [[colorscheme nord]]
